"""OAuth Authorization-Code + PKCE flow for Claude and Codex.

Implements:
- PKCE S256 verifier/challenge generation
- Authorization URL construction (user opens in browser)
- Authorization code exchange for access + refresh tokens
  (per-provider body encoding: JSON for Claude, form for Codex)
- Token refresh (mirrors existing per-collector refresh logic)
- id_token JWT claim extraction (Codex account_id)

Uses only httpx — no additional dependencies.
No user secrets or account-specific data are stored in this module.

Paste-back flow note (Codex):
  The redirect URI is http://localhost:1455/auth/callback (allow-listed by
  OpenAI). ModelDeck runs on the HA host, not the user's PC, so the redirect
  won't load in the browser. The user copies the ``?code=...`` value from the
  browser's address bar and pastes it into the web UI.
"""

from __future__ import annotations

import base64
import hashlib
import json
import secrets
import urllib.parse
from typing import Any

import httpx

from modeldeck.auth.provider_specs import ProviderOAuthSpec
from modeldeck.core.logging import get_logger

logger = get_logger(__name__)

# PKCE verifier length in bytes (43–128 chars in base64url after encoding).
_PKCE_VERIFIER_BYTES = 48


class OAuthFlowError(Exception):
    """Raised when an OAuth flow step fails."""


# ---------------------------------------------------------------------------
# PKCE helpers
# ---------------------------------------------------------------------------

def generate_verifier() -> str:
    """Generate a cryptographically random PKCE code verifier (base64url, no padding)."""
    raw = secrets.token_bytes(_PKCE_VERIFIER_BYTES)
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode("ascii")


def derive_challenge(verifier: str) -> str:
    """Derive S256 PKCE code challenge from a verifier."""
    digest = hashlib.sha256(verifier.encode("ascii")).digest()
    return base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")


def generate_state() -> str:
    """Generate a random OAuth state parameter."""
    return secrets.token_urlsafe(24)


# ---------------------------------------------------------------------------
# Authorization URL
# ---------------------------------------------------------------------------

def build_authorize_url(
    spec: ProviderOAuthSpec,
    verifier: str,
    state: str,
) -> str:
    """Build the authorization URL the user must open in their browser.

    Parameters
    ----------
    spec:
        Provider OAuth spec (from provider_specs.py).
    verifier:
        PKCE code verifier (generated by generate_verifier()).
    state:
        Random state token (generated by generate_state()).

    Returns
    -------
    str
        URL to open in a browser. ModelDeck will wait for the user to paste
        back the authorization code (or the full redirect URL).
    """
    challenge = derive_challenge(verifier)
    params: list[tuple[str, str]] = [
        ("response_type", "code"),
        ("client_id", spec.effective_client_id),
        ("redirect_uri", spec.effective_redirect_uri),
        ("scope", " ".join(spec.effective_scopes)),
        ("state", state),
        ("code_challenge", challenge),
        ("code_challenge_method", "S256"),
    ]
    # Append provider-specific extra params (e.g. Codex originator).
    params.extend(spec.effective_extra_authorize_params)
    return spec.effective_authorize_url + "?" + urllib.parse.urlencode(params)


# ---------------------------------------------------------------------------
# Code exchange
# ---------------------------------------------------------------------------

async def exchange_code(
    spec: ProviderOAuthSpec,
    code: str,
    verifier: str,
    *,
    state: str | None = None,
    client: httpx.AsyncClient | None = None,
) -> dict[str, Any]:
    """Exchange an authorization code for access and refresh tokens.

    Parameters
    ----------
    spec:
        Provider OAuth spec.
    code:
        Authorization code returned by the provider (user pastes this).
        May contain a trailing ``#state`` fragment — it is stripped here
        so the bare code is sent to the token endpoint.
    verifier:
        The PKCE verifier used when building the authorize URL.
    state:
        The OAuth state value.  Required by some providers (e.g. Claude)
        in the token exchange body.  Ignored when
        ``spec.effective_token_exchange_includes_state`` is False.
    client:
        Optional httpx client (for testing).

    Returns
    -------
    dict
        Full token response payload. Contains at minimum ``access_token``.
        May contain ``refresh_token``, ``id_token``, ``expires_in``,
        ``token_type``.

    Raises
    ------
    OAuthFlowError
        If the exchange fails (HTTP error or missing access_token).
    """
    # Defensively strip a bare CODE#STATE that callers may not have split.
    clean_code, embedded_state = parse_code_and_state(code) if "#" in code else (code.strip(), None)
    effective_state = state or embedded_state

    body: dict[str, str] = {
        "grant_type": "authorization_code",
        "code": clean_code,
        "redirect_uri": spec.effective_redirect_uri,
        "client_id": spec.effective_client_id,
        "code_verifier": verifier,
    }
    if spec.effective_token_exchange_includes_state and effective_state:
        body["state"] = effective_state
    return await _post_token(spec, body, client=client)


# ---------------------------------------------------------------------------
# Token refresh
# ---------------------------------------------------------------------------

async def refresh_tokens(
    spec: ProviderOAuthSpec,
    refresh_token: str,
    *,
    client: httpx.AsyncClient | None = None,
) -> dict[str, Any]:
    """Exchange a refresh token for a new access token.

    Parameters
    ----------
    spec:
        Provider OAuth spec.
    refresh_token:
        The refresh token to exchange.
    client:
        Optional httpx client (for testing).

    Returns
    -------
    dict
        Token response payload.

    Raises
    ------
    OAuthFlowError
        If the refresh fails.
    """
    body = {
        "grant_type": "refresh_token",
        "refresh_token": refresh_token,
        "client_id": spec.effective_client_id,
        "scope": " ".join(spec.effective_scopes),
    }
    return await _post_token(spec, body, client=client)


# ---------------------------------------------------------------------------
# id_token claim extraction
# ---------------------------------------------------------------------------

def decode_id_token_claims(id_token: str) -> dict[str, Any]:
    """Decode the payload claims of a JWT id_token (no signature verification).

    Only the middle (payload) segment is decoded; the signature is not
    verified because this is our own freshly-obtained token from the issuer
    and we only need claim values for local persistence (account_id, etc.).

    Parameters
    ----------
    id_token:
        A JWT string in ``header.payload.signature`` format.

    Returns
    -------
    dict
        Decoded claims, or an empty dict if the token cannot be parsed.
    """
    try:
        parts = id_token.split(".")
        if len(parts) < 2:
            return {}
        # Base64url-decode with padding.
        payload_b64 = parts[1]
        padding = 4 - (len(payload_b64) % 4)
        if padding != 4:
            payload_b64 += "=" * padding
        raw = base64.urlsafe_b64decode(payload_b64)
        return json.loads(raw)  # type: ignore[no-any-return]
    except Exception:
        return {}


def extract_codex_account_id(id_token: str) -> str | None:
    """Extract the ChatGPT account_id from a Codex id_token.

    The Codex CLI stores the ``chatgpt_account_id`` inside the nested
    ``https://api.openai.com/auth`` object in the JWT payload.

    Parameters
    ----------
    id_token:
        JWT id_token received from the Codex OAuth token endpoint.

    Returns
    -------
    str or None
        The account_id value, or None if not found.
    """
    claims = decode_id_token_claims(id_token)
    auth_block = claims.get("https://api.openai.com/auth")
    if isinstance(auth_block, dict):
        account_id = auth_block.get("chatgpt_account_id")
        if isinstance(account_id, str) and account_id:
            return account_id
    return None


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

async def _post_token(
    spec: ProviderOAuthSpec,
    body: dict[str, str],
    *,
    client: httpx.AsyncClient | None = None,
) -> dict[str, Any]:
    """POST to the token endpoint using the provider's required encoding.

    Codex requires ``application/x-www-form-urlencoded``; Claude uses JSON.
    The encoding is determined by ``spec.effective_token_encoding``.
    """
    url = spec.effective_token_url
    encoding = spec.effective_token_encoding  # "json" or "form"
    try:
        if encoding == "form":
            # Send as application/x-www-form-urlencoded (Codex requirement).
            if client is not None:
                response = await client.post(url, data=body, timeout=30.0)
            else:
                async with httpx.AsyncClient(timeout=30.0) as c:
                    response = await c.post(url, data=body)
        else:
            # Default: send as JSON (Claude).
            if client is not None:
                response = await client.post(url, json=body, timeout=30.0)
            else:
                async with httpx.AsyncClient(timeout=30.0) as c:
                    response = await c.post(url, json=body)
        response.raise_for_status()
        payload: dict[str, Any] = response.json()
    except httpx.HTTPStatusError as exc:
        raise OAuthFlowError(
            f"Token endpoint returned {exc.response.status_code}"
        ) from exc
    except httpx.HTTPError as exc:
        raise OAuthFlowError(f"Token endpoint request failed: {type(exc).__name__}") from exc

    if not payload.get("access_token"):
        raise OAuthFlowError("Token response missing access_token")

    return payload


def parse_code_and_state(raw: str) -> tuple[str, str | None]:  # noqa: C901
    """Parse an authorization code (and optional state) from whatever the user pasted.

    Handles all forms a user might paste from their browser:

    * Full URL with scheme: ``http://localhost:1455/auth/callback?code=abc&state=xyz``
    * Full URL (Claude console): ``https://console.anthropic.com/…?code=abc&state=xyz``
    * Code in URL fragment: ``https://example.com/callback#code=abc&state=xyz``
    * Scheme-less URL: ``localhost:1455/auth/callback?code=abc&state=xyz``
    * Bare ``code=VALUE`` param: ``code=ac_abc123``
    * Bare ``CODE#STATE`` (Claude console display format): ``ac_abc123#randomstate``
    * Bare authorization code: ``ac_abc123``

    Returns
    -------
    (code, state)
        ``code`` is the authorization code (never empty).
        ``state`` is the state value or ``None`` when not present.

    Raises
    ------
    OAuthFlowError
        When no code can be extracted.
    """
    # Strip surrounding whitespace and common wrapping characters.
    stripped = raw.strip().strip("<>\"'\u2018\u2019\u201c\u201d")

    if not stripped:
        raise OAuthFlowError(
            "Nothing to parse — paste the full URL from your browser's address bar "
            "or the authorization code shown on the provider's page."
        )

    # --- bare "code=VALUE[&state=…]" param (no URL, no scheme) ---
    if stripped.lower().startswith("code="):
        rest = stripped[5:]
        parts = rest.split("&", 1)
        code = parts[0].strip()
        if not code:
            raise OAuthFlowError(
                "No value found after 'code=' — paste the full URL from your "
                "browser's address bar."
            )
        state: str | None = None
        if len(parts) > 1:
            for param in parts[1].split("&"):
                if param.lower().startswith("state="):
                    state = param[6:].strip() or None
                    break
        return code, state

    # --- URL-shaped input (with or without scheme) ---
    parse_target = stripped
    if not stripped.lower().startswith(("http://", "https://")):
        # Scheme-less URL heuristic: has a path separator and a query string.
        if "/" in stripped and "?" in stripped:
            parse_target = "https://" + stripped

    if parse_target.lower().startswith(("http://", "https://")):
        parsed = urllib.parse.urlparse(parse_target)
        # Check query string first, then fragment (some providers put params after #).
        for source in (parsed.query, parsed.fragment):
            params = urllib.parse.parse_qs(source)
            code_list = params.get("code", [])
            if code_list and code_list[0].strip():
                code = code_list[0].strip()
                state_list = params.get("state", [])
                state = state_list[0].strip() if state_list else None
                return code, state or None
        raise OAuthFlowError(
            "No 'code' parameter found in the URL. "
            "Copy the entire address-bar URL from your browser and paste it here."
        )

    # --- bare CODE#STATE (Claude console displays code#state on the page) ---
    if "#" in stripped:
        code_part, _, state_part = stripped.partition("#")
        code_part = code_part.strip()
        state_part = state_part.strip()
        if code_part:
            return code_part, state_part or None
        raise OAuthFlowError(
            "Could not extract a code from the pasted value. "
            "Copy the entire URL or just the code from the provider's page."
        )

    # --- bare code (no URL, no prefix, no fragment) ---
    return stripped, None


def extract_code_from_redirect(redirect_url: str) -> str:
    """Extract the authorization code from whatever the user pasted.

    Thin wrapper around :func:`parse_code_and_state` that returns only the
    code.  Accepts the same input formats — full URL, scheme-less URL,
    ``code=VALUE``, bare ``CODE#STATE``, or bare code.

    For providers that require the state value in the token exchange (e.g.
    Claude), use :func:`parse_code_and_state` directly.
    """
    code, _ = parse_code_and_state(redirect_url)
    return code
