"""OAuth Authorization-Code + PKCE flow for Claude and Codex.

Implements:
- PKCE S256 verifier/challenge generation
- Authorization URL construction (user opens in browser)
- Authorization code exchange for access + refresh tokens
  (per-provider body encoding: JSON for Claude, form for Codex)
- Token refresh (mirrors existing per-collector refresh logic)
- id_token JWT claim extraction (Codex account_id)

Uses only httpx — no additional dependencies.
No user secrets or account-specific data are stored in this module.

Paste-back flow note (Codex):
  The redirect URI is http://localhost:1455/auth/callback (allow-listed by
  OpenAI). ModelDeck runs on the HA host, not the user's PC, so the redirect
  won't load in the browser. The user copies the ``?code=...`` value from the
  browser's address bar and pastes it into the web UI.
"""

from __future__ import annotations

import base64
import hashlib
import json
import secrets
import urllib.parse
from typing import Any

import httpx

from modeldeck.auth.provider_specs import ProviderOAuthSpec
from modeldeck.core.logging import get_logger

logger = get_logger(__name__)

# PKCE verifier length in bytes (43–128 chars in base64url after encoding).
_PKCE_VERIFIER_BYTES = 48


class OAuthFlowError(Exception):
    """Raised when an OAuth flow step fails."""


# ---------------------------------------------------------------------------
# PKCE helpers
# ---------------------------------------------------------------------------

def generate_verifier() -> str:
    """Generate a cryptographically random PKCE code verifier (base64url, no padding)."""
    raw = secrets.token_bytes(_PKCE_VERIFIER_BYTES)
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode("ascii")


def derive_challenge(verifier: str) -> str:
    """Derive S256 PKCE code challenge from a verifier."""
    digest = hashlib.sha256(verifier.encode("ascii")).digest()
    return base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")


def generate_state() -> str:
    """Generate a random OAuth state parameter."""
    return secrets.token_urlsafe(24)


# ---------------------------------------------------------------------------
# Authorization URL
# ---------------------------------------------------------------------------

def build_authorize_url(
    spec: ProviderOAuthSpec,
    verifier: str,
    state: str,
) -> str:
    """Build the authorization URL the user must open in their browser.

    Parameters
    ----------
    spec:
        Provider OAuth spec (from provider_specs.py).
    verifier:
        PKCE code verifier (generated by generate_verifier()).
    state:
        Random state token (generated by generate_state()).

    Returns
    -------
    str
        URL to open in a browser. ModelDeck will wait for the user to paste
        back the authorization code (or the full redirect URL).
    """
    challenge = derive_challenge(verifier)
    params: list[tuple[str, str]] = [
        ("response_type", "code"),
        ("client_id", spec.effective_client_id),
        ("redirect_uri", spec.effective_redirect_uri),
        ("scope", " ".join(spec.effective_scopes)),
        ("state", state),
        ("code_challenge", challenge),
        ("code_challenge_method", "S256"),
    ]
    # Append provider-specific extra params (e.g. Codex originator).
    params.extend(spec.effective_extra_authorize_params)
    return spec.effective_authorize_url + "?" + urllib.parse.urlencode(params)


# ---------------------------------------------------------------------------
# Code exchange
# ---------------------------------------------------------------------------

async def exchange_code(
    spec: ProviderOAuthSpec,
    code: str,
    verifier: str,
    *,
    client: httpx.AsyncClient | None = None,
) -> dict[str, Any]:
    """Exchange an authorization code for access and refresh tokens.

    Parameters
    ----------
    spec:
        Provider OAuth spec.
    code:
        Authorization code returned by the provider (user pastes this).
    verifier:
        The PKCE verifier used when building the authorize URL.
    client:
        Optional httpx client (for testing).

    Returns
    -------
    dict
        Full token response payload. Contains at minimum ``access_token``.
        May contain ``refresh_token``, ``id_token``, ``expires_in``,
        ``token_type``.

    Raises
    ------
    OAuthFlowError
        If the exchange fails (HTTP error or missing access_token).
    """
    body = {
        "grant_type": "authorization_code",
        "code": code.strip(),
        "redirect_uri": spec.effective_redirect_uri,
        "client_id": spec.effective_client_id,
        "code_verifier": verifier,
    }
    return await _post_token(spec, body, client=client)


# ---------------------------------------------------------------------------
# Token refresh
# ---------------------------------------------------------------------------

async def refresh_tokens(
    spec: ProviderOAuthSpec,
    refresh_token: str,
    *,
    client: httpx.AsyncClient | None = None,
) -> dict[str, Any]:
    """Exchange a refresh token for a new access token.

    Parameters
    ----------
    spec:
        Provider OAuth spec.
    refresh_token:
        The refresh token to exchange.
    client:
        Optional httpx client (for testing).

    Returns
    -------
    dict
        Token response payload.

    Raises
    ------
    OAuthFlowError
        If the refresh fails.
    """
    body = {
        "grant_type": "refresh_token",
        "refresh_token": refresh_token,
        "client_id": spec.effective_client_id,
        "scope": " ".join(spec.effective_scopes),
    }
    return await _post_token(spec, body, client=client)


# ---------------------------------------------------------------------------
# id_token claim extraction
# ---------------------------------------------------------------------------

def decode_id_token_claims(id_token: str) -> dict[str, Any]:
    """Decode the payload claims of a JWT id_token (no signature verification).

    Only the middle (payload) segment is decoded; the signature is not
    verified because this is our own freshly-obtained token from the issuer
    and we only need claim values for local persistence (account_id, etc.).

    Parameters
    ----------
    id_token:
        A JWT string in ``header.payload.signature`` format.

    Returns
    -------
    dict
        Decoded claims, or an empty dict if the token cannot be parsed.
    """
    try:
        parts = id_token.split(".")
        if len(parts) < 2:
            return {}
        # Base64url-decode with padding.
        payload_b64 = parts[1]
        padding = 4 - (len(payload_b64) % 4)
        if padding != 4:
            payload_b64 += "=" * padding
        raw = base64.urlsafe_b64decode(payload_b64)
        return json.loads(raw)  # type: ignore[no-any-return]
    except Exception:
        return {}


def extract_codex_account_id(id_token: str) -> str | None:
    """Extract the ChatGPT account_id from a Codex id_token.

    The Codex CLI stores the ``chatgpt_account_id`` inside the nested
    ``https://api.openai.com/auth`` object in the JWT payload.

    Parameters
    ----------
    id_token:
        JWT id_token received from the Codex OAuth token endpoint.

    Returns
    -------
    str or None
        The account_id value, or None if not found.
    """
    claims = decode_id_token_claims(id_token)
    auth_block = claims.get("https://api.openai.com/auth")
    if isinstance(auth_block, dict):
        account_id = auth_block.get("chatgpt_account_id")
        if isinstance(account_id, str) and account_id:
            return account_id
    return None


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

async def _post_token(
    spec: ProviderOAuthSpec,
    body: dict[str, str],
    *,
    client: httpx.AsyncClient | None = None,
) -> dict[str, Any]:
    """POST to the token endpoint using the provider's required encoding.

    Codex requires ``application/x-www-form-urlencoded``; Claude uses JSON.
    The encoding is determined by ``spec.effective_token_encoding``.
    """
    url = spec.effective_token_url
    encoding = spec.effective_token_encoding  # "json" or "form"
    try:
        if encoding == "form":
            # Send as application/x-www-form-urlencoded (Codex requirement).
            if client is not None:
                response = await client.post(url, data=body, timeout=30.0)
            else:
                async with httpx.AsyncClient(timeout=30.0) as c:
                    response = await c.post(url, data=body)
        else:
            # Default: send as JSON (Claude).
            if client is not None:
                response = await client.post(url, json=body, timeout=30.0)
            else:
                async with httpx.AsyncClient(timeout=30.0) as c:
                    response = await c.post(url, json=body)
        response.raise_for_status()
        payload: dict[str, Any] = response.json()
    except httpx.HTTPStatusError as exc:
        raise OAuthFlowError(
            f"Token endpoint returned {exc.response.status_code}"
        ) from exc
    except httpx.HTTPError as exc:
        raise OAuthFlowError(f"Token endpoint request failed: {type(exc).__name__}") from exc

    if not payload.get("access_token"):
        raise OAuthFlowError("Token response missing access_token")

    return payload


def extract_code_from_redirect(redirect_url: str) -> str:  # noqa: C901
    """Extract the authorization code from whatever the user pasted.

    Designed to be forgiving: accepts any of the following without the user
    having to understand the OAuth flow:

    * Full redirect URL with ``http``/``https`` scheme:
        ``http://localhost:1455/auth/callback?code=abc&state=xyz``
        ``https://console.anthropic.com/oauth/code/callback?code=abc``
    * Code in URL fragment (some providers put params after ``#``):
        ``https://example.com/callback#code=abc&state=xyz``
    * Scheme-less URL pasted from the address bar:
        ``localhost:1455/auth/callback?code=abc&state=xyz``
    * Bare ``code=VALUE`` param string (user copies just that part):
        ``code=ac_rpcQfsO0Dgx80xz9zG2an3FCMGl``
    * Bare authorization code (no prefix, no URL):
        ``ac_rpcQfsO0Dgx80xz9zG2an3FCMGl``

    Surrounding whitespace, angle-brackets (``<url>``), and straight or
    curly quotes are stripped before processing.

    Paste-back usage note
    ---------------------
    For Codex the redirect goes to ``http://localhost:1455/auth/callback``
    which is the user's *browser machine* localhost — not the add-on host —
    so that page fails to load.  The user copies the entire URL from the
    address bar and pastes it here; this function extracts the ``code=``
    value automatically.

    For Claude the redirect goes to
    ``https://console.anthropic.com/oauth/code/callback`` which renders and
    displays the code.  The user can paste either the full page URL or the
    code value shown on that page.
    """
    # Strip surrounding whitespace and common wrapping characters.
    stripped = redirect_url.strip().strip("<>\"'\u2018\u2019\u201c\u201d")

    # --- bare "code=VALUE" param (no URL, no scheme) ---
    if stripped.lower().startswith("code="):
        code = stripped[5:].split("&")[0].strip()
        if code:
            return code
        raise OAuthFlowError(
            "No value found after 'code=' — paste the full URL from your "
            "browser's address bar."
        )

    # --- URL-shaped input (with or without scheme) ---
    # Normalise scheme-less URLs so urlparse can handle them.
    parse_target = stripped
    if not stripped.lower().startswith(("http://", "https://")):
        # Heuristic: contains a slash and a query string → looks like a URL.
        if "/" in stripped and "?" in stripped:
            parse_target = "https://" + stripped

    if parse_target.lower().startswith(("http://", "https://")):
        parsed = urllib.parse.urlparse(parse_target)

        # Check query string first, then fragment (some providers use #code=).
        for source in (parsed.query, parsed.fragment):
            params = urllib.parse.parse_qs(source)
            code = params.get("code", [""])[0].strip()
            if code:
                return code

        raise OAuthFlowError(
            "No 'code' parameter found in the URL. "
            "Copy the entire address-bar URL from your browser and paste it here."
        )

    # --- bare code (no URL, no prefix) ---
    if stripped:
        return stripped

    raise OAuthFlowError(
        "Nothing to parse — paste the full URL from your browser's address bar "
        "or the authorization code shown on the provider's page."
    )
