"""OAuth Authorization-Code + PKCE flow for Claude and Codex.

Implements:
- PKCE S256 verifier/challenge generation
- Authorization URL construction (user opens in browser)
- Authorization code exchange for access + refresh tokens
- Token refresh (mirrors existing per-collector refresh logic)

Uses only httpx — no additional dependencies.
No user secrets or account-specific data are stored in this module.
"""

from __future__ import annotations

import base64
import hashlib
import secrets
import urllib.parse
from typing import Any

import httpx

from modeldeck.auth.provider_specs import ProviderOAuthSpec
from modeldeck.core.logging import get_logger

logger = get_logger(__name__)

# PKCE verifier length in bytes (43–128 chars in base64url after encoding).
_PKCE_VERIFIER_BYTES = 48


class OAuthFlowError(Exception):
    """Raised when an OAuth flow step fails."""


# ---------------------------------------------------------------------------
# PKCE helpers
# ---------------------------------------------------------------------------

def generate_verifier() -> str:
    """Generate a cryptographically random PKCE code verifier (base64url, no padding)."""
    raw = secrets.token_bytes(_PKCE_VERIFIER_BYTES)
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode("ascii")


def derive_challenge(verifier: str) -> str:
    """Derive S256 PKCE code challenge from a verifier."""
    digest = hashlib.sha256(verifier.encode("ascii")).digest()
    return base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")


def generate_state() -> str:
    """Generate a random OAuth state parameter."""
    return secrets.token_urlsafe(24)


# ---------------------------------------------------------------------------
# Authorization URL
# ---------------------------------------------------------------------------

def build_authorize_url(
    spec: ProviderOAuthSpec,
    verifier: str,
    state: str,
) -> str:
    """Build the authorization URL the user must open in their browser.

    Parameters
    ----------
    spec:
        Provider OAuth spec (from provider_specs.py).
    verifier:
        PKCE code verifier (generated by generate_verifier()).
    state:
        Random state token (generated by generate_state()).

    Returns
    -------
    str
        URL to open in a browser. ModelDeck will wait for the user to paste
        back the authorization code (or the full redirect URL).
    """
    challenge = derive_challenge(verifier)
    params = {
        "response_type": "code",
        "client_id": spec.effective_client_id,
        "redirect_uri": spec.effective_redirect_uri,
        "scope": " ".join(spec.effective_scopes),
        "state": state,
        "code_challenge": challenge,
        "code_challenge_method": "S256",
    }
    return spec.effective_authorize_url + "?" + urllib.parse.urlencode(params)


# ---------------------------------------------------------------------------
# Code exchange
# ---------------------------------------------------------------------------

async def exchange_code(
    spec: ProviderOAuthSpec,
    code: str,
    verifier: str,
    *,
    client: httpx.AsyncClient | None = None,
) -> dict[str, Any]:
    """Exchange an authorization code for access and refresh tokens.

    Parameters
    ----------
    spec:
        Provider OAuth spec.
    code:
        Authorization code returned by the provider (user pastes this).
    verifier:
        The PKCE verifier used when building the authorize URL.
    client:
        Optional httpx client (for testing).

    Returns
    -------
    dict
        Token response payload containing at minimum ``access_token``.
        May contain ``refresh_token``, ``expires_in``, ``token_type``.

    Raises
    ------
    OAuthFlowError
        If the exchange fails (HTTP error or missing access_token).
    """
    body = {
        "grant_type": "authorization_code",
        "code": code.strip(),
        "redirect_uri": spec.effective_redirect_uri,
        "client_id": spec.effective_client_id,
        "code_verifier": verifier,
    }
    return await _post_token(spec, body, client=client)


# ---------------------------------------------------------------------------
# Token refresh
# ---------------------------------------------------------------------------

async def refresh_tokens(
    spec: ProviderOAuthSpec,
    refresh_token: str,
    *,
    client: httpx.AsyncClient | None = None,
) -> dict[str, Any]:
    """Exchange a refresh token for a new access token.

    Parameters
    ----------
    spec:
        Provider OAuth spec.
    refresh_token:
        The refresh token to exchange.
    client:
        Optional httpx client (for testing).

    Returns
    -------
    dict
        Token response payload.

    Raises
    ------
    OAuthFlowError
        If the refresh fails.
    """
    body = {
        "grant_type": "refresh_token",
        "refresh_token": refresh_token,
        "client_id": spec.effective_client_id,
        "scope": " ".join(spec.effective_scopes),
    }
    return await _post_token(spec, body, client=client)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

async def _post_token(
    spec: ProviderOAuthSpec,
    body: dict[str, str],
    *,
    client: httpx.AsyncClient | None = None,
) -> dict[str, Any]:
    """POST to the token endpoint and validate the response."""
    url = spec.effective_token_url
    try:
        if client is not None:
            response = await client.post(url, json=body, timeout=30.0)
        else:
            async with httpx.AsyncClient(timeout=30.0) as c:
                response = await c.post(url, json=body)
        response.raise_for_status()
        payload: dict[str, Any] = response.json()
    except httpx.HTTPStatusError as exc:
        raise OAuthFlowError(
            f"Token endpoint returned {exc.response.status_code}"
        ) from exc
    except httpx.HTTPError as exc:
        raise OAuthFlowError(f"Token endpoint request failed: {type(exc).__name__}") from exc

    if not payload.get("access_token"):
        raise OAuthFlowError("Token response missing access_token")

    return payload


def extract_code_from_redirect(redirect_url: str) -> str:
    """Extract the authorization code from a redirect URL or bare code string.

    Accepts either the full redirect URL (e.g.
    ``https://modeldeck.local/oauth/callback?code=abc&state=xyz``) or just
    the bare code string that the user copied from the browser.
    """
    stripped = redirect_url.strip()
    if stripped.startswith("http"):
        parsed = urllib.parse.urlparse(stripped)
        params = urllib.parse.parse_qs(parsed.query)
        code = params.get("code", [""])[0]
        if not code:
            raise OAuthFlowError(
                "No 'code' parameter found in redirect URL"
            )
        return code
    return stripped
