name: Semgrep

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  schedule:
    - cron: "0 7 * * 0"

permissions:
  contents: read

concurrency:
  group: semgrep-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semgrep:
    uses: automationnexus/.github/.github/workflows/semgrep.yml@v1
